### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by MoistMan420** [Brighter-bits/MathsWatch-Bot#2]
Struggles with giving answers with square numbers 
![image](https://github.com/Brighter-bits/MathsWatch-Bot/assets/134065767/b4f46e05-b976-45f9-811c-670ea7403eff)

**Comment by Brighter-bits** [comment]
I'm not exactly sure what you are referring to, especially with the picture

The first unanswered question does not contain a square number. Are you using the latest version? As I believe the first questions error was solved by v0.0.2 and works in my environment

**Comment by Brighter-bits** [comment]
You have not replied after a week and it seems what you were looking for was fixed anyway.

Closed Issue
